name: output information
on:  workflow_dispatch
jobs:
    first-job:
        runs-on: windows-latest
        steps:
            - name: output github context
              run: echo "${{toJson(github)}}"
    
